### ISSUE TITLE
Phone number in the table should be clickable

### ISSUE THREAD

**Issue by jigar1101** [COVID19-Resources-India/covid19resourcesindia#34]
Phone number should be clickable i.e on clicking, it directly takes the user to call.

There are cases in this as the data is not very organized, there may be multiple numbers, different formats, blank etc.

One way to do this would be may validate the number in the field to be a valid contact number of India.
If it is valid then make it hyperlinked otherwise shown it as a text (How it is shown currently)

**Comment by Jaspreet099** [comment]
can i work on this issue?

**Comment by miteshsawant** [comment]
@Jaspreet099 Sure, thanks for helping!

**Comment by Jaspreet099** [comment]
@miteshsawant  as mentioned in the issue that we have to add the telephone numbers in the link. 

Can you share with me the Screenshot or the name of the pages where I have to do the respective changes - It will be very helpful

**Comment by miteshsawant** [comment]
@Jaspreet099 The idea is to have all phone numbers in the table be "clickable". Just a basic `anchor` tag with `tel:` in the `href`

**Comment by Jaspreet099** [comment]
> @Jaspreet099 The idea is to have all phone numbers in the table be "clickable". Just a basic `anchor` tag with `tel:` in the `href`

ok thanks, I'll update you on this

**Comment by Jaspreet099** [comment]
@miteshsawant can you tell me the exact file name

**Comment by Jaspreet099** [comment]
> @Jaspreet099 The idea is to have all phone numbers in the table be "clickable". Just a basic `anchor` tag with `tel:` in the `href`

in which file all phone numbers get stored ?

**Comment by radhasatam** [comment]
@js

> > @Jaspreet099 The idea is to have all phone numbers in the table be "clickable". Just a basic `anchor` tag with `tel:` in the `href`
> 
> in which file all phone numbers get stored ?

This PR might help: https://github.com/COVID19-Resources-India/covid19resourcesindia/pull/36
If the column name is: "Telephone", you can render a `<Telephone>` component that returns a `<a href="tel:` link instead.

**Comment by jigar1101** [comment]
Looks like it's required now will take this up.

**Comment by Jaspreet099** [comment]
> Looks like it's required now will take this up.

I have use that `tel:` tag but its not working on website

**Comment by jigar1101** [comment]
No worries I'll take this up and create a PR, you can check it out.
