### ISSUE TITLE
Make Helpful Guidelines & Official Documents Information dyanmic

### ISSUE THREAD

**Issue by jigar1101** [COVID19-Resources-India/covid19resourcesindia#35]
The data below is hardcoded currently, need to make it dynamic similar to other pages where the data is fetched through the sheet with the help of firebase.

![image](https://user-images.githubusercontent.com/3745587/115713485-ad6c2d80-a393-11eb-919e-9ee36ff7ba93.png)

**Comment by radhasatam** [comment]
Additional Info: The key for this data in the db is `${SPREADSHEET_KEY}/guidelines-and-updates`. It has the columns - 

- State (National / state name)
- Type (Latest Update / Official Document / Guideline)
- Text
- Link. 

We can fetch all "National" links right now. Can figure out how to make this data contextual in a different issue.
