### ISSUE TITLE
Sync Mobile header with the Desktop Header

### ISSUE THREAD

**Issue by jigar1101** [COVID19-Resources-India/covid19resourcesindia#37]
**Desktop Header**

![image](https://user-images.githubusercontent.com/3745587/115714585-e527a500-a394-11eb-964c-6e9219ed38e7.png)

**Mobile Header**

![image](https://user-images.githubusercontent.com/3745587/115714298-9843ce80-a394-11eb-87c3-30e7b9760174.png)

**Comment by radhasatam** [comment]
This should never go out of sync ideally. The info in header should be reused for desktop and mobile.
