### ISSUE TITLE
Twitter Integration

### ISSUE THREAD

**Issue by jigar1101** [COVID19-Resources-India/covid19resourcesindia#38]
Integrate Twitter API to show the real-time data on the website based on certain keywords.

This feed will be shown next to the Table on the Category pages.

So for example, if the user has selected the state Maharashtra and oxygen cylinders. It should show related relevant tweets.

So the feed is dependent on the state and category.

**Comment by radhasatam** [comment]
If the API limits are too restrictive, maybe we should fall back to at least redirecting them to Twitter based on their context (state / category). Similar to what this website: https://covid19-twitter.in/
